### ISSUE TITLE
Error when selecting an NC program after running Color Holes

### ISSUE THREAD

**Issue by npolanosky** [TheEppicJR/Color-Holes-for-Fusion360#1]
If I select an NC program in a file where Color Holes has been used, I get the following error popup: 

`Failed:
Traceback (most recent call last):
  File "E:/Organized Things/Work Stuff/Fusion Addins/Color-Holes-for-Fusion360-main/Color Holes.py", line 86, in notify
    if len(sels) == 1 and sels[0].entity.objectType == "adsk::fusion::BRepFace":
  File "C:\Users/npola/AppData/Local/Autodesk/webdeploy/pre-production/19107935ce2ad08720646cb4a31efe37d8a5f41b/Api/Python/packages\adsk\core.py", line 14821, in _get_entity
    return _core.Selection__get_entity(self)
RuntimeError: 3 : It is an unknown type of CAM object.`

**Comment by TheEppicJR** [comment]
I can't really do anything about this until they fix/improve some parts of the Fusion API, I made a post on the forums about it on the API forum:
https://forums.autodesk.com/t5/fusion-360-api-and-scripts/selection-object-entity-fails-with-runtimeerror-3-when-a-setups/td-p/11088871
